### ISSUE TITLE
Support TD40

### ISSUE THREAD

**Issue by edestecd** [spbrogan/sensor.mopeka_pro_check#25]
I would like to add support for https://www.mopekaiot.com/product/mopeka-td40 here and in esphome.

I'm working on contacting them to see if they will work with me before I order one.
Hoping that the BLE packets are similar or the same

**Comment by edestecd** [comment]
If you know who you worked with at mopeka that may be helpful

**Comment by spbrogan** [comment]
I got lucky once and had some communication, but I have since tried to communicate and never got a response.   I think I did use their sales channel to initiate the conversation.  So maybe you will get somewhere.  I would appreciate hearing back and adding support if you get anything.  I have other questions like can i turn down the sensor report rate (not the app rate) to save power on the sensor.  It isn't like propane or water needs once per second report rates.  

I do know that VictronEnergy has since got info from Mopeka and done an integration.  I haven't looked but they might have a B2B relationship that might get higher priority.  
https://github.com/victronenergy/dbus-ble-sensors/tree/master/src
